### ISSUE TITLE
can't gen image

### ISSUE THREAD

**Issue by gdtiti** [internationalTD/defuser#1]
Traceback (most recent call last):
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\gradio\routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\gradio\blocks.py", line 739, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\gradio\blocks.py", line 638, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\gradio\components.py", line 2118, in preprocess
    return process_single_file(x)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\gradio\components.py", line 2088, in process_single_file
    f["name"],
TypeError: 'int' object is not subscriptable

**Comment by internationalTD** [comment]
Should be fixed in v0.0.2, released today.
