### ISSUE TITLE
when i reinstall stable-diffusion-webui gen images error

### ISSUE THREAD

**Issue by gdtiti** [internationalTD/defuser#2]
Traceback (most recent call last):
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__    raise exc
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__    await self.app(scope, receive, sender)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\routing.py", line 68, in app
    await response(scope, receive, send)
  File "I:\xStableDiffusion\v1.2 full\python\Lib\site-packages\starlette\responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path I:\xStableDiffusion\v1.2 full\stable-diffusion-webui\null does not exist.

**Comment by gdtiti** [comment]
{"data":[["data:image/png;base64, ... "],"{\"prompt\": \"1girl\", \"all_prompts\": [\"1girl\"], \"negative_prompt\": \"\", \"seed\": 1658673643, \"all_seeds\": [1658673643], \"subseed\": 3473276129, \"all_subseeds\": [3473276129], \"subseed_strength\": 0, \"width\": 512, \"height\": 512, \"sampler_index\": 0, \"sampler\": \"Euler a\", \"cfg_scale\": 7, \"steps\": 20, \"batch_size\": 1, \"restore_faces\": false, \"face_restoration_model\": null, \"sd_model_hash\": \"925997e9\", \"seed_resize_from_w\": 0, \"seed_resize_from_h\": 0, \"denoising_strength\": null, \"extra_generation_params\": {}, \"index_of_first_image\": 0, \"infotexts\": [\"1girl\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1658673643, Size: 512x512, Model hash: 925997e9\"], \"styles\": [\"None\", \"None\"], \"job_timestamp\": \"20221023115938\", \"clip_skip\": 1}","<p>1girl<br>\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1658673643, Size: 512x512, Model hash: 925997e9</p><div class='performance'><p class='time'>Time taken: <wbr>1.68s</p><p class='vram'>Torch active/reserved: 2615/3304 MiB, <wbr>Sys VRAM: 4988/24576 MiB (20.3%)</p></div>"],"is_generating":false,"duration":1.6787586212158203,"average_duration":7.263638377189636}

i find info is not 'name' so request fetch_remote_png methon is error

**Comment by gdtiti** [comment]
i find info is not 'name' so request fetch_remote_png methon is error

**Comment by internationalTD** [comment]
Should be fixed in v0.0.2, released today. 

Please download the new release and update your WebUI installation. It looks like you have an old WebUI and defuser only handles the new output format.
