### ISSUE TITLE
After plugin install Krita don't start

### ISSUE THREAD

**Issue by valden80** [internationalTD/defuser#7]
Krita 5.1.1, Manjaro Linux.

After installing lastest version, of plugin, Krita don't start anymore. It's show up this error, then close:

TypeError
Python 3.10.7: /usr/bin/python3
Tue Nov  1 22:04:15 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'Defuser.MyDocker.MyDocker'>

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in __init__(self=<Defuser.MyDocker.MyDocker object>)
  296         super().__init__()
  297         # src/MyDocker.hx:28
  298         host_App.init(self)
  299         # src/MyDocker.hx:31
  300         # src/MyDocker.hx:31
global host_App = <class 'Defuser.MyDocker.host_App'>
host_App.init = <function host_App.init>
self = <Defuser.MyDocker.MyDocker object>

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in init(v=<Defuser.MyDocker.MyDocker object>)
 2602         req.onData = _hx_local_15
 2603         # src/host/App.hx:140
 2604         req.request(False)
 2605         # src/host/App.hx:143
 2606         v.setWindowTitle("Defuser")
req = <Defuser.MyDocker.sys_Http object>
req.request = <bound method sys_Http.request of <Defuser.MyDocker.sys_Http object>>

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in request(self=<Defuser.MyDocker.sys_Http object>, post=False)
 5247         # C:\HaxeToolkit\haxe\std/sys/Http.hx:69
 5248         if (not err):
 5249             self.success(output.getBytes())
 5250 
 5251     def customRequest(self,post,api,sock = None,method = None):
self = <Defuser.MyDocker.sys_Http object>
self.success = <bound method haxe_http_HttpBase.success of <Defuser.MyDocker.sys_Http object>>
output = <Defuser.MyDocker.haxe_io_BytesOutput object>
output.getBytes = <bound method haxe_io_BytesOutput.getBytes of <Defuser.MyDocker.haxe_io_BytesOutput object>>

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in success(self=<Defuser.MyDocker.sys_Http object>, data=<Defuser.MyDocker.haxe_io_Bytes object>)
 2119         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:235
 2120         if self.hasOnData():
 2121             self.onData(self.get_responseData())
 2122         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:238
 2123         self.onBytes(self.responseBytes)
self = <Defuser.MyDocker.sys_Http object>
self.onData = <function host_App.init.<locals>._hx_local_15>
self.get_responseData = <bound method haxe_http_HttpBase.get_responseData of <Defuser.MyDocker.sys_Http object>>

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in _hx_local_15(data_out='<!DOCTYPE html>\n<html lang="en" style="margin: 0....padding = "0";\n\t\t\t}\n\t\t</script>\n\t</body>\n</html>')
 2599             print(str(host_UI.tags.h.get("img2img",None)))
 2600             # src/host/App.hx:137
 2601             host_UI.createInterface()
 2602         req.onData = _hx_local_15
 2603         # src/host/App.hx:140
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.createInterface = <function host_UI.createInterface>

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in createInterface()
 2772         host_UI.makeTab("txt2img")
 2773         # src/host/UI.python.hx:66
 2774         host_UI.makeTab("img2img")
 2775         # src/host/UI.python.hx:69
 2776         # src/host/UI.python.hx:69
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.makeTab = <function host_UI.makeTab>

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in makeTab(mode='img2img')
 2854             _g = (_g + 1)
 2855             # src/host/UI.python.hx:116
 2856             widget = host_UI.makeComponent(comp,mode)
 2857             # src/host/UI.python.hx:117
 2858             formlayout.addWidget(widget)
widget = <PyQt5.QtWidgets.QGroupBox object>
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.makeComponent = <function host_UI.makeComponent>
comp = {'id': 335, 'props': {'label': 'Mask precision',...param_name': 'mask_precision'}, 'type': 'slider'}
mode = 'img2img'

 /home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py in makeComponent(component={'id': 335, 'props': {'label': 'Mask precision',...param_name': 'mask_precision'}, 'type': 'slider'}, mode='img2img')
 3250                     raise "Class cast error"
 3251                 return _hx_local_21
 3252             input3.setMinimum(_hx_local_22())
 3253             # src/host/UI.python.hx:361
 3254             def _hx_local_24():
input3 = <PyQt5.QtWidgets.QSpinBox object>
input3.setMinimum = <built-in method setMinimum of QSpinBox object>
_hx_local_22 = <function host_UI.makeComponent.<locals>._hx_local_22>
TypeError: setMinimum(self, int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("setMinimum(self, int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 298, in __init__
    host_App.init(self)
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 2604, in init
    req.request(False)
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 5249, in request
    self.success(output.getBytes())
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 2121, in success
    self.onData(self.get_responseData())
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 2601, in _hx_local_15
    host_UI.createInterface()
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 2774, in createInterface
    host_UI.makeTab("img2img")
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 2856, in makeTab
    widget = host_UI.makeComponent(comp,mode)
  File "/home/usersd/.local/share/krita/pykrita/Defuser/MyDocker.py", line 3252, in makeComponent
    input3.setMinimum(_hx_local_22())
TypeError: setMinimum(self, int): argument 1 has unexpected type 'float'

**Comment by internationalTD** [comment]
I installed the latest version of txt2mask from [here](https://github.com/ThereforeGames/txt2mask) , since I found no other script/extension that adds a "'Mask precision" slider, but I was unable to reproduce this error as of yet. I'll clean the UI generation code and see if that fixes it.

**Comment by if-ai** [comment]
> I installed the latest version of txt2mask from [here](https://github.com/ThereforeGames/txt2mask) , since I found no other script/extension that adds a "'Mask precision" slider, but I was unable to reproduce this error as of yet. I'll clean the UI generation code and see if that fixes it.

I installed text2Mask and still have the same problem  here is the log . The first time I install it defuser pane was empty without icons I try installing from file the hopeful fix but didn't worked so I udated krita from 5.1 to 5.1.3 but now it doesn't start and have this error AttributeError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Tue Nov  8 12:51:15 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Program Files\Krita (x64)\lib\krita-python-libs\krita\dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'Defuser.MyDocker.MyDocker'>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in __init__(self=<Defuser.MyDocker.MyDocker object>)
  296         super().__init__()
  297         # src/MyDocker.hx:28
  298         host_App.init(self)
  299         # src/MyDocker.hx:31
  300         # src/MyDocker.hx:31
global host_App = <class 'Defuser.MyDocker.host_App'>
host_App.init = <function host_App.init>
self = <Defuser.MyDocker.MyDocker object>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in init(v=<Defuser.MyDocker.MyDocker object>)
 2602         req.onData = _hx_local_15
 2603         # src/host/App.hx:140
 2604         req.request(False)
 2605         # src/host/App.hx:143
 2606         v.setWindowTitle("Defuser")
req = <Defuser.MyDocker.sys_Http object>
req.request = <bound method sys_Http.request of <Defuser.MyDocker.sys_Http object>>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in request(self=<Defuser.MyDocker.sys_Http object>, post=False)
 5247         # C:\HaxeToolkit\haxe\std/sys/Http.hx:69
 5248         if (not err):
 5249             self.success(output.getBytes())
 5250 
 5251     def customRequest(self,post,api,sock = None,method = None):
self = <Defuser.MyDocker.sys_Http object>
self.success = <bound method haxe_http_HttpBase.success of <Defuser.MyDocker.sys_Http object>>
output = <Defuser.MyDocker.haxe_io_BytesOutput object>
output.getBytes = <bound method haxe_io_BytesOutput.getBytes of <Defuser.MyDocker.haxe_io_BytesOutput object>>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in success(self=<Defuser.MyDocker.sys_Http object>, data=<Defuser.MyDocker.haxe_io_Bytes object>)
 2119         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:235
 2120         if self.hasOnData():
 2121             self.onData(self.get_responseData())
 2122         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:238
 2123         self.onBytes(self.responseBytes)
self = <Defuser.MyDocker.sys_Http object>
self.onData = <function host_App.init.<locals>._hx_local_15>
self.get_responseData = <bound method haxe_http_HttpBase.get_responseData of <Defuser.MyDocker.sys_Http object>>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in _hx_local_15(data_out='<!DOCTYPE html>\n<html lang="en" style="margin: 0....padding = "0";\n\t\t\t}\n\t\t</script>\n\t</body>\n</html>')
 2599             print(str(host_UI.tags.h.get("img2img",None)))
 2600             # src/host/App.hx:137
 2601             host_UI.createInterface()
 2602         req.onData = _hx_local_15
 2603         # src/host/App.hx:140
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.createInterface = <function host_UI.createInterface>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in createInterface()
 2800         host_UI.makeTab("inpaint")
 2801         # src/host/UI.python.hx:77
 2802         host_UI.makeTab("outpainting_mk2")
 2803 
 2804     @staticmethod
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.makeTab = <function host_UI.makeTab>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in makeTab(mode='outpainting_mk2')
 2974             req.onStatus = _hx_local_6
 2975             # src/host/UI.python.hx:203
 2976             req.request(True)
 2977 
 2978     @staticmethod
req = <Defuser.MyDocker.sys_Http object>
req.request = <bound method sys_Http.request of <Defuser.MyDocker.sys_Http object>>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in request(self=<Defuser.MyDocker.sys_Http object>, post=True)
 5247         # C:\HaxeToolkit\haxe\std/sys/Http.hx:69
 5248         if (not err):
 5249             self.success(output.getBytes())
 5250 
 5251     def customRequest(self,post,api,sock = None,method = None):
self = <Defuser.MyDocker.sys_Http object>
self.success = <bound method haxe_http_HttpBase.success of <Defuser.MyDocker.sys_Http object>>
output = <Defuser.MyDocker.haxe_io_BytesOutput object>
output.getBytes = <bound method haxe_io_BytesOutput.getBytes of <Defuser.MyDocker.haxe_io_BytesOutput object>>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in success(self=<Defuser.MyDocker.sys_Http object>, data=<Defuser.MyDocker.haxe_io_Bytes object>)
 2119         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:235
 2120         if self.hasOnData():
 2121             self.onData(self.get_responseData())
 2122         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:238
 2123         self.onBytes(self.responseBytes)
self = <Defuser.MyDocker.sys_Http object>
self.onData = <function host_UI.makeTab.<locals>._hx_local_5>
self.get_responseData = <bound method haxe_http_HttpBase.get_responseData of <Defuser.MyDocker.sys_Http object>>

 C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in _hx_local_5(data_out='{"data":[{"visible":false,"__type__":"update"},{...ing":false,"duration":0.0,"average_duration":0.0}')
 2959                     # src/host/UI.python.hx:187
 2960                     value = Reflect.field((data[i] if i >= 0 and i < len(data) else None),"visible")
 2961                     setattr(tag_props,(("_hx_" + "visible") if (("visible" in python_Boot.keywords)) else (("_hx_" + "visible") if (((((len("visible") > 2) and ((ord("visible"[0]) == 95))) and ((ord("visible"[1]) == 95))) and ((ord("visible"[(len("visible") - 1)]) != 95)))) else "visible")),value)
 2962                     # src/host/UI.python.hx:188
 2963                     if (Reflect.field((vismap[i] if i >= 0 and i < len(vismap) else None),"container") is not None):
builtinsetattr = <built-in function setattr>
tag_props = None
global python_Boot = <class 'Defuser.MyDocker.python_Boot'>
python_Boot.keywords = {'False', 'None', 'True', 'and', 'as', 'assert', ...}
builtinlen = <built-in function len>
builtinord = <built-in function ord>
value = False
AttributeError: 'NoneType' object has no attribute 'visible'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'visible'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Program Files\Krita (x64)\lib\krita-python-libs\krita\dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 298, in __init__
    host_App.init(self)
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2604, in init
    req.request(False)
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 5249, in request
    self.success(output.getBytes())
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2121, in success
    self.onData(self.get_responseData())
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2601, in _hx_local_15
    host_UI.createInterface()
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2802, in createInterface
    host_UI.makeTab("outpainting_mk2")
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2976, in makeTab
    req.request(True)
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 5249, in request
    self.success(output.getBytes())
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2121, in success
    self.onData(self.get_responseData())
  File "C:\Users\SoyYo\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2961, in _hx_local_5
    setattr(tag_props,(("_hx_" + "visible") if (("visible" in python_Boot.keywords)) else (("_hx_" + "visible") if (((((len("visible") > 2) and ((ord("visible"[0]) == 95))) and ((ord("visible"[1]) == 95))) and ((ord("visible"[(len("visible") - 1)]) != 95)))) else "visible")),value)
AttributeError: 'NoneType' object has no attribute 'visible'

**Comment by internationalTD** [comment]
Thank you for reporting this jvoxel. I was able to reproduce your error. Introduced with a recent commit in auto's webui somewhere. I have an idea about a fix already.

Just so we are clear: I inferred that valden80 had txt2mask from his error log, but that script is NOT needed for defuser to start. 
And as far as I can tell, it does not have anything to do with your error on startup either.

**Comment by if-ai** [comment]
Hi thank you for looking at the issue. I wasn't sure it was the same error, just same behavior where krita stops after installation. 
I do have 3 other krita SD plugins installed it might be that but none have the same name or folders so, I don't see why that would conflict. 
I am interested on using your plugin because it seems to have a better workflow and outpainting from what I read on the github page.
Thanks.

**Comment by evan-mckee** [comment]
My krita also crashes and won't open, reporting this error:


TypeError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Sun Nov 26 20:11:35 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Program Files\Krita (x64)\lib\krita-python-libs\krita\dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'Defuser.MyDocker.MyDocker'>

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in __init__(self=<Defuser.MyDocker.MyDocker object>)
  296         super().__init__()
  297         # src/MyDocker.hx:28
  298         host_App.init(self)
  299         # src/MyDocker.hx:31
  300         # src/MyDocker.hx:31
global host_App = <class 'Defuser.MyDocker.host_App'>
host_App.init = <function host_App.init>
self = <Defuser.MyDocker.MyDocker object>

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in init(v=<Defuser.MyDocker.MyDocker object>)
 2602         req.onData = _hx_local_15
 2603         # src/host/App.hx:140
 2604         req.request(False)
 2605         # src/host/App.hx:143
 2606         v.setWindowTitle("Defuser")
req = <Defuser.MyDocker.sys_Http object>
req.request = <bound method sys_Http.request of <Defuser.MyDocker.sys_Http object>>

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in request(self=<Defuser.MyDocker.sys_Http object>, post=False)
 5247         # C:\HaxeToolkit\haxe\std/sys/Http.hx:69
 5248         if (not err):
 5249             self.success(output.getBytes())
 5250 
 5251     def customRequest(self,post,api,sock = None,method = None):
self = <Defuser.MyDocker.sys_Http object>
self.success = <bound method haxe_http_HttpBase.success of <Defuser.MyDocker.sys_Http object>>
output = <Defuser.MyDocker.haxe_io_BytesOutput object>
output.getBytes = <bound method haxe_io_BytesOutput.getBytes of <Defuser.MyDocker.haxe_io_BytesOutput object>>

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in success(self=<Defuser.MyDocker.sys_Http object>, data=<Defuser.MyDocker.haxe_io_Bytes object>)
 2119         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:235
 2120         if self.hasOnData():
 2121             self.onData(self.get_responseData())
 2122         # C:\HaxeToolkit\haxe\std/haxe/http/HttpBase.hx:238
 2123         self.onBytes(self.responseBytes)
self = <Defuser.MyDocker.sys_Http object>
self.onData = <function host_App.init.<locals>._hx_local_15>
self.get_responseData = <bound method haxe_http_HttpBase.get_responseData of <Defuser.MyDocker.sys_Http object>>

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in _hx_local_15(data_out='<!doctype html>\n<html\n\tlang="en"\n\tstyle="\n\t\tmarg...pan/style.css?1701022136.9847772"></body>\n</html>')
 2599             print(str(host_UI.tags.h.get("img2img",None)))
 2600             # src/host/App.hx:137
 2601             host_UI.createInterface()
 2602         req.onData = _hx_local_15
 2603         # src/host/App.hx:140
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.createInterface = <function host_UI.createInterface>

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in createInterface()
 2770         host_App.docker.setWidget(widget)
 2771         # src/host/UI.python.hx:65
 2772         host_UI.makeTab("txt2img")
 2773         # src/host/UI.python.hx:66
 2774         host_UI.makeTab("img2img")
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.makeTab = <function host_UI.makeTab>

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in makeTab(mode='txt2img')
 2854             _g = (_g + 1)
 2855             # src/host/UI.python.hx:116
 2856             widget = host_UI.makeComponent(comp,mode)
 2857             # src/host/UI.python.hx:117
 2858             formlayout.addWidget(widget)
widget = <PyQt5.QtWidgets.QGroupBox object>
global host_UI = <class 'Defuser.MyDocker.host_UI'>
host_UI.makeComponent = <function host_UI.makeComponent>
comp = {'id': 143, 'type': 'radio', 'props': {'choices'...o': False}, 'example_inputs': {'serialized': []}}
mode = 'txt2img'

 C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py in makeComponent(component={'id': 143, 'type': 'radio', 'props': {'choices'...o': False}, 'example_inputs': {'serialized': []}}, mode='txt2img')
 3138             input1 = QComboBox()
 3139             # src/host/UI.python.hx:324
 3140             input1.addItems(Reflect.field(props,"choices"))
 3141             # src/host/UI.python.hx:325
 3142             hbox.addWidget(input1)
input1 = <PyQt5.QtWidgets.QComboBox object>
input1.addItems = <built-in method addItems of QComboBox object>
global Reflect = <class 'Defuser.MyDocker.Reflect'>
Reflect.field = <function Reflect.field>
props = {'choices': [['positive', 'positive'], ['negativ... ['gradio-radio'], 'param_name': 'select_prompt'}
TypeError: index 0 has type 'list' but 'str' is expected
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("index 0 has type 'list' but 'str' is expected",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Program Files\Krita (x64)\lib\krita-python-libs\krita\dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 298, in __init__
    host_App.init(self)
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2604, in init
    req.request(False)
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 5249, in request
    self.success(output.getBytes())
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2121, in success
    self.onData(self.get_responseData())
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2601, in _hx_local_15
    host_UI.createInterface()
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2772, in createInterface
    host_UI.makeTab("txt2img")
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 2856, in makeTab
    widget = host_UI.makeComponent(comp,mode)
  File "C:\Users\evanm\AppData\Roaming\krita\pykrita\Defuser\MyDocker.py", line 3140, in makeComponent
    input1.addItems(Reflect.field(props,"choices"))
TypeError: index 0 has type 'list' but 'str' is expected
